apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-broker
  name: kafka-service
  namespace: kafka
spec:
  clusterIP: "None"
  ports:
  - port: 9092
#  - port: 9093
#  - port: 9094
  selector:
    app: kafka-broker
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: kafka-broker
  name: kafka-broker
  namespace: kafka
spec:
  serviceName: kafka-service
  replicas: 3
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      hostname: kafka-broker
      containers:
      - env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: 10.96.178.180:2181
        - name: KAFKA_LISTENERS
          value: BROKER_0://:9092,BROKER_1://:9093,BROKER_2://:9094
        - name: KAFKA_ADVERTISED_LISTENERS
          value: BROKER_0://kafka-broker-0:9092,BROKER_1://kafka-broker-1:9093,BROKER_2://kafka-broker-2:9094
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: BROKER_0:PLAINTEXT,BROKER_1:PLAINTEXT,BROKER_2:PLAINTEXT
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: BROKER_0
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka-broker-0:9092
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka-broker-0
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        name: kafka-broker
        ports:
          - containerPort: 9092
          - containerPort: 9093
          - containerPort: 9094

