apiVersion: v1
kind: Service
metadata:
  name: kafka-service-loadbalancer
  namespace: kafka
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 9092
  selector:
    app: kafka-broker


