version: '3.7'

services:
  sbt:
    image: sbt-builder:2.13
    volumes:
      - sbt-data:/root/.ivy2
      - sbt-data:/root/.cache
      - .:/opt
    working_dir: /opt
    environment:
      - _JAVA_OPTIONS="-Xmx1g"
      - INPUT_TOPIC=input-topic
      - OUTPUT_TOPIC=output-topic
    networks:
     - kafka

volumes:
  sbt-data:
    name: sbt-data

networks:
  kafka:
    external: true